# This workflow file is named 'more-ci' and is used to run additional CI checks
# that complement the main CI workflow. It ensures that our code is tested
# across multiple operating systems and OCaml compiler versions.
#
# Compared to the main 'ci.yml' job, this skips some steps that are not
# necessary to check for every combination of os and ocaml-compiler, such as
# generating coverage report, linting odoc, opam and fmt, etc.
#
# We prefer to keep it separate from the main CI workflow because we find it
# more readable, over having too many conditional steps in the same job.

name: more-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**" # This will match pull requests targeting any branch

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - 5.3.x
          - 5.2.x
          - 4.14.x
        exclude:
          # We exclude the combination already tested in the 'ci' workflow.
          - os: ubuntu-latest
            ocaml-compiler: 5.3.x
          # We exclude windows-4.14 - this fails when building core.
          - os: windows-latest
            ocaml-compiler: 4.14.x

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@dec6499fef64fc5d7ed43d43a87251b7b1c306f5 # v3.4.8
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
            mbarbin: https://github.com/mbarbin/opam-repository.git
      #     alpha:   https://github.com/kit-ty-kate/opam-alpha-repository.git
      #     janestreet-bleeding: https://github.com/janestreet/opam-repository.git
      #     janestreet-bleeding-external: https://github.com/janestreet/opam-repository.git#external-packages

      - name: Environment setup
        run: |
          PACKAGES=$(script/ci-packages/run.sh "${{ matrix.os }}" "${{ matrix.ocaml-compiler }}" dune)
          OPAM_PACKAGES=$(script/ci-packages/run.sh "${{ matrix.os }}" "${{ matrix.ocaml-compiler }}" opam)
          echo "PACKAGES=$PACKAGES" >> "$GITHUB_ENV"
          echo "OPAM_PACKAGES=$OPAM_PACKAGES" >> "$GITHUB_ENV"

      # We build and run tests for a subset of packages. More tests are run in
      # the development workflow and as part of the main CI job. These are the
      # tests that are checked for every combination of os and ocaml-compiler.
      - name: Install dependencies
        run: opam install ${{ env.OPAM_PACKAGES }} --deps-only --with-test

      - name: Build & Run tests
        run: opam exec -- dune build @all @runtest --only-packages=${{ env.PACKAGES }}
